---
# File to config rasberry pis
# you need to copy your ssh keys to the pi in order for this to work
# ansible-playbook -i inventories/hosts -u pi provision_pi.yml
- hosts: pis
  become: yes
  gather_facts: true


  pre_tasks:
    - name: Set Timezone to America/New_York
      timezone:
        name: America/New_York

    - name: Install system packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - wget
        - nano
        - curl
        - rsync
        - vim
        - git
        - zip



  roles:
    - apache_flask

  # Some config borrowed from here:
  # Source: https://raspberrypi.stackexchange.com/questions/28907/how-could-one-automate-the-raspbian-raspi-config-setup
  tasks:


    # - name: Disable GUI and enable CLI auto-login
    #   become: yes
    #   command: raspi-config nonint do_boot_behaviour

    - name: Enable PI Camera
      become: yes
      command: raspi-config nonint do_camera 0

    - name: Install python 3.x
      apt:
        name: python3
        state: present

    # to control GPIO pins
    - name: Install RPI.GPIO
      become: yes
      command: pip3 install RPI.GPIO

    # Python web framework
    - name: Install Flask
      become: yes
      command: pip3 install flask

    # https://learn.adafruit.com/adafruit-pitft-28-inch-resistive-touchscreen-display-raspberry-pi/easy-install-2
    - name: Download files to install lcd screen
      get_url:
          url: https://raw.githubusercontent.com/adafruit/Raspberry-Pi-Installer-Scripts/master/adafruit-pitft.sh
          dest: /home/pi/

    - name: set permission for Downloaded files
      become: yes
      command: chmod +x adafruit-pitft.sh
    # now this must be run manually:
    # sudo ./adafruit-pitft.sh

    - name: copy .bash_profile to ~/
      copy:
        src: .bash_profile
        dest: /home/pi/


  post_tasks:
    - name: reboot PIs
      reboot:
